### PR TITLE
Switch source generators to incremental generators

### LINKED ISSUE #11: Code Generators degrade VS performance, add excessive load to Roslyn Analyzers and high CPU utilization
## Describe the bug

Visual Studio C# Code Editors get very sluggish, Roslyn Analyzer with high CPU usage. No actual work can really get done in the editors.

- [X] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:
Not observed on 7.0.2, after update to 7.1 this is showing. Reverting back to 7.0.2 is fixing this. Seems to be the Source Generators are loading up CPU to >50% up to 90% with the Roslyn Code Analyzers load.

## Steps to Reproduce

1. Update from 7.0.2 to 7.1 on a large project (unit is a 4 Core i7 with 4GB RAM on Windows 2012 Server development system).
2. Start to code.
3. Regular background utilization of >50% from Roslyn Code Analyzer, editing is sluggish, and not really possible.
4. Revert back to 7.0.2
5. Performance is back as used, VS is responsive again.

## Expected behavior

Update to 7.1 should not degrade VS performance in editing, building.

NuGet Package(s): 7.1

Package Version(s):

Visual Studio version:

- [X] 2019 (16.11.3)

### LINKED ISSUE #13: MVVM Source Generators: CS1028 Error if #region block
Compilation fails for the Microsoft MVVM Toolkit source generator and a #region block.
(error CS1028: Unexpected preprocessor directive)

## Describe the bug

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

```
namespace App3
{
    #region Region
    public class Region
    {
    }
    #endregion

    public partial class ViewModel
    {
        [ICommand]
        private void Greet() { }
    }
}
```

## Environment

NuGet Package(s): Microsoft.Toolkit.Mvvm
Package Version(s): 7.1.1

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

Device form factor:

- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [x] 2022 (17.{minor_version})

## Additional context

(Duplicate of https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4225 ?)

### LINKED ISSUE #37: Switch MVVM Toolkit generators to incremental generators
**Contributes to #8**

Now that VS2022 is officially out, we should migrate all existing source generators in the MVVM Toolkit to be incremental generators. This will bring a major performance improvement to the IDE responsiveness and typing experience, as the current approach using non-incremental generators based on `SyntaxReceiver`-s has known scalability issues with large solutions.

### LINKED ISSUE #57: Editor Issues While Using `[ObservableProperty]`
## Describe the bug

While making use of the new `[ObservableProperty]` source generator, and potentially the other new generators, accessing the injected property names (and potentially other injected code) causes the editor to show errors. 

As an example, here is a simple ViewModel that can reproduce the error:
```csharp
namespace Launcher.ViewModel;

using CommunityToolkit.Mvvm.ComponentModel;

public partial class AboutViewModel : ObservableObject
{
    public AboutViewModel()
    {
        this.Test1 = "Hello world.";
    }

    [ObservableProperty]
    private string _test1;
}
```

Visual Studio marks a few things here that may need to be fixed:

 - The constructor is marked with a warning saying:
```
CS8618	Non-nullable field '_test1' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```

_This warning will appear regardless if you access the fields using the attribute or not. Just having the ctor is enough for them to cause this warning._

 - The `set_` field access is marked as an error saying:
```
CS1061	'AboutViewModel' does not contain a definition for 'Test1' and no accessible extension method 'Test1' accepting a first argument of type 'AboutViewModel' could be found (are you missing a using directive or an assembly reference?)
```

- The field itself is marked as:
```
IDE0044: Make field readonly.
```

_This last one is kind of annoying since it puts the grey squares in the scrollbar of the editor for every single property that will make use of this source generator now._

To help visualize this, here is a screenshot of what my editor looks like using the above code:

devenv_aGxkpLhk0N

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [x] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)

Steps to reproduce the behavior: (In a new project)

1. Open VS2022, create a new project of your type choosing. (In my case, I am using WPF)
2. Add a ViewModel folder and inside of it, add a new AboutViewModel class.
3. Add a using to `using CommunityToolkit.Mvvm.ComponentModel;`.
4. Change the class definition to `partial`.
5. Add a private string property using the `[ObservableProperty]` attribute as shown above in the example code. (Name it `_test1`)
6. Add a constructor. You should see the 2nd issue already now.
7. Attempt to access the known injected property name in this new constructor. (`this.Test1 = "Hello";`) You should see the first issue now.
8. You should also see the third issue already as well.

Steps to reproduce the behavior: (In the sample app)

1. Clone the sample app repository.
2. Open the Sample App in VS2022. (In my case, testing with the `MvvmSampleUwp.sln`)
3. Update the project dependencies to latest Mvvm community toolkit version. (From 7.0.3 to 7.1.2 in Nuget manager.)
4. Open the MvvmSample.Core > ViewModels > SamplePageViewModel.cs
5. Change the class type to `partial`.
6. Add a private string property using the `[ObservableProperty]` attribute as shown above in the example code. (Name it `_test1`)
7. You should now see the second and third problem already. The constructor will warn about the field and the field will suggest being marked readonly.
8. Attempt to access the known injected property name in this new constructor. (`this.Test1 = "Hello";`) You should see the first issue now.

## Expected behavior

Based on the examples given and shown in the blog post about these new generators, there should be no errors, warnings, or suggestions while using the `[ObservableProperty]` attribute.

## Screenshots

_See above, the picture fits better with the explanation above than being separated and posted here._

## Environment

NuGet Package(s): 
Package Version(s):
  - CommunityToolkit.Mvvm (7.1.2)
  - Microsoft.Extensions.DependencyInjection (6.0.0)

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
- [x] November 2021 Update (21H2)

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
- [x] November 2021 Update (21H2)

Device form factor:

- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [x] 2022 (17.0.2)

### LINKED ISSUE #58: Small Typo In ObservableProperty XML Docs
## Describe the bug

_I wasn't sure if this belonged in the other 'Docs' repo tracker, so I'll report it here since the code typo is within this repo._

There is a small typo in the XML doc for `[ObservableProperty]` found here:
https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/37caf88b68463ebb23b67c2e5d3f095485c9ecc5/Microsoft.Toolkit.Mvvm/ComponentModel/Attributes/ObservablePropertyAttribute.cs#L43

This should be `isEnabled` rather than `name`.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)

1. No steps needed, just a typo in the doc.

## Expected behavior

N/A

## Screenshots

N/A

## Environment

NuGet Package(s): CommunityToolkit.Mvvm

Package Version(s): 7.1.2

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
- [x] November 2021 Update (21H2)

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
- [x] November 2021 Update (21H2)

Device form factor:

- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [x] 2022 (17.0.2)

## Additional context

N/A

### PR DESCRIPTION
**Pull request by Sergio0694**
**Contributes to #8**
**Closes #11**
**Closes #13**
**Closes #37**
**Closes #57**
**Closes #58**

This PR changes the implementation of all source generators in the MVVM Toolkit to be incremental generators.
It also lowers the minimum C# version requirement to C# 8 (down from C# 9) for source generators.

### CODE REVIEW

File: ThirdPartyNotices.txt [hunk 1]
```diff
@@ -11,6 +11,7 @@ This project incorporates components from the projects listed below. The origina
 4.  PrivateObject/PrivateType (https://github.com/microsoft/testfx/tree/664ac7c2ac9dbfbee9d2a0ef560cfd72449dfe34/src/TestFramework/Extension.Desktop), included in UnitTests.
 5.  QuinnDamerell/UniversalMarkdown (https://github.com/QuinnDamerell/UniversalMarkdown) contributed by Quinn Damerell and Paul Bartrum for the MarkdownTextBlock control, relicensed to this .NET Foundation project under the MIT license upon contribution in https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/772.
 6.  qmatteoq/DesktopBridgeHelpers commit e278153 (https://github.com/qmatteoq/DesktopBridgeHelpers), contributed by Matteo Pagani to identify if running with identity in DesktopNotificationManagerCompat.cs and DesktopBridgeHelpers.cs, relicensed to this .NET Foundation project under the MIT license upon contribution in https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/3457.
+6.  Sergio0694/ComputeSharp (https://github.com/Sergio0694/ComputeSharp), contributed by Sergio Pedri to reuse some helpers to support incremental generators in the MVVM Toolkit.
```
Comment (XAML-Knight) [inline ThirdPartyNotices.txt:14]: 7, not 6

**Review by XAML-Knight — CHANGES_REQUESTED** [review]
Looks good - found a small typo.  I ran a test on VS2022, x64, WPF, .NET 6

File: ThirdPartyNotices.txt (hunk 1 above)
Comment (Sergio0694) [reply ThirdPartyNotices.txt]: Whoops! Fixed, thanks! 😄

**Review by XAML-Knight — APPROVED** [review]

File: CommunityToolkit.Mvvm.SourceGenerators/ComponentModel/Models/TypedConstantInfo.Factory.cs [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+            ImmutableArray<TypedConstantInfo> items = arg.Values.Select(From).ToImmutableArray();
+
+            return new Array(elementTypeName, items);
+        }
+
+        return (arg.Kind, arg.Value) switch
+        {
+            (TypedConstantKind.Primitive, string text) => new Primitive.String(text),
+            (TypedConstantKind.Primitive, bool flag) => new Primitive.Boolean(flag),
+            (TypedConstantKind.Primitive, object value) => value switch
```
[the remark this answers is not in the document]
Comment (Sergio0694) [reply CommunityToolkit.Mvvm.SourceGenerators/ComponentModel/Models/TypedConstantInfo.Factory.cs:40]: That's not a valid type for attribute parameters according to the C# spec 🙃
Unfortunately it wasn't my decision here. See [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#attribute-parameter-types) for more info.

File: CommunityToolkit.Mvvm.SourceGenerators/EmbeddedResources/ObservableObject.cs [hunk 3]
```diff
@@ -447,7 +450,10 @@ async void MonitorTask()
                 OnPropertyChanged(propertyName);
             }
 
-            callback(newValue);
+            if (callback != null)
```
[the remark this answers is not in the document]
Comment (Sergio0694) [reply CommunityToolkit.Mvvm.SourceGenerators/EmbeddedResources/ObservableObject.cs]: It's the same. I just left this as `!=` to avoid diverging from the reference here:

https://github.com/CommunityToolkit/dotnet/blob/de2355c1c9c937f850f887092f8219f374f9f400/CommunityToolkit.Mvvm/ComponentModel/ObservableObject.cs#L510-L513

This way this file will remain as close as possible, since it's meant to basically be a mirror. Couldn't use `is not null` here because that requires C# 9, and I wanted the generated code to only require C# 8 instead. I've added an explicit cast in 3c9dc47302f82a8bd1eb0888b61da4d1415746f2 just for good measure and to possibly help the codegen, good catch!

File: CommunityToolkit.Mvvm.SourceGenerators/Extensions/INamedTypeSymbolExtensions.cs [hunk 4]
```diff
@@ -35,34 +35,22 @@ static StringBuilder BuildFrom(ISymbol? symbol, StringBuilder builder)
...
-    /// <summary>
-    /// Gets a valid filename for a given <see cref="INamedTypeSymbol"/> instance.
-    /// </summary>
-    /// <param name="symbol">The input <see cref="INamedTypeSymbol"/> instance.</param>
-    /// <returns>The full metadata name for <paramref name="symbol"/> that is also a valid filename.</returns>
-    [Pure]
-    public static string GetFullMetadataNameForFileName(this INamedTypeSymbol symbol)
-    {
-        return symbol.GetFullMetadataName().Replace('`', '-').Replace('+', '.');
+        return BuildFrom(symbol, new StringBuilder(256)).ToString().Replace('`', '-').Replace('+', '.');
```
[the remark this answers is not in the document]
Comment (Sergio0694) [reply CommunityToolkit.Mvvm.SourceGenerators/Extensions/INamedTypeSymbolExtensions.cs:42]: Sure thing! Done in f871ee97c5fa13adedc225ec5181238fd83028c3 👍
